version: "3.8"
services:
  redis:
    container_name: redis
    image: redis:6.2.6-alpine
    labels:
      - name=redis
      - mode=standalone
    ports:
      - ${REDIS_BINDING_PORT}:6379
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes: # 마운트할 볼륨 설정
      - ${REDIS_DATA_PATH}:/data
      - ${REDIS_CONFIG_FILE}:/usr/local/etc/redis/redis.conf
      #- ${REDIS_USER_FILE}:/etc/redis/users.acl
    #restart: always
  maria:
    container_name: maria
    image: mariadb:10
    ports:
      - ${MARIA_BINDING_PORT}:3306
    #command: 
    volumes:
      - ${MARIA_DATA_PATH}:/var/lib/mysql
      - ${MARIA_CONFIG_FILE}:/etc/mysql/conf.d
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    #restart: always
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - ${MONGO_BINDING_PORT}:27017
    volumes:
      - ${MONGO_DATA_PATH}:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD} 
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
      #restart: always